//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingDocumentInfo", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    [System.SerializableAttribute()]
    public partial class BillingDocumentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DocumentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DocumentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DocumentDate {
            get {
                return this.DocumentDateField;
            }
            set {
                if ((this.DocumentDateField.Equals(value) != true)) {
                    this.DocumentDateField = value;
                    this.RaisePropertyChanged("DocumentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DocumentId {
            get {
                return this.DocumentIdField;
            }
            set {
                if ((this.DocumentIdField.Equals(value) != true)) {
                    this.DocumentIdField = value;
                    this.RaisePropertyChanged("DocumentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationFault", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiBatchFault))]
    public partial class ApplicationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingId {
            get {
                return this.TrackingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingIdField, value) != true)) {
                    this.TrackingIdField = value;
                    this.RaisePropertyChanged("TrackingId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    public partial class AdApiFaultDetail : MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApplicationFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiError[] ErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiFault", Namespace="https://bingads.microsoft.com/Customer/v9/Exception")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiBatchFault))]
    public partial class ApiFault : MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApplicationFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.OperationError[] OperationErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.OperationError[] OperationErrors {
            get {
                return this.OperationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationErrorsField, value) != true)) {
                    this.OperationErrorsField = value;
                    this.RaisePropertyChanged("OperationErrors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiBatchFault", Namespace="https://bingads.microsoft.com/Customer/v9/Exception")]
    [System.SerializableAttribute()]
    public partial class ApiBatchFault : MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BatchError[] BatchErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BatchError[] BatchErrors {
            get {
                return this.BatchErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchErrorsField, value) != true)) {
                    this.BatchErrorsField = value;
                    this.RaisePropertyChanged("BatchErrors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationError", Namespace="https://bingads.microsoft.com/Customer/v9/Exception")]
    [System.SerializableAttribute()]
    public partial class OperationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdApiError", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    public partial class AdApiError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchError", Namespace="https://bingads.microsoft.com/Customer/v9/Exception")]
    [System.SerializableAttribute()]
    public partial class BatchError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    public enum DataType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xml = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pdf = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingDocument", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    [System.SerializableAttribute()]
    public partial class BillingDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.DataType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.DataType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertionOrder", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    [System.SerializableAttribute()]
    public partial class InsertionOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> BalanceAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookingCountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> InsertionOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> LastModifiedByUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> NotificationThresholdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SpendCapAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrderStatus> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchaseOrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> BalanceAmount {
            get {
                return this.BalanceAmountField;
            }
            set {
                if ((this.BalanceAmountField.Equals(value) != true)) {
                    this.BalanceAmountField = value;
                    this.RaisePropertyChanged("BalanceAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BookingCountryCode {
            get {
                return this.BookingCountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingCountryCodeField, value) != true)) {
                    this.BookingCountryCodeField = value;
                    this.RaisePropertyChanged("BookingCountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> InsertionOrderId {
            get {
                return this.InsertionOrderIdField;
            }
            set {
                if ((this.InsertionOrderIdField.Equals(value) != true)) {
                    this.InsertionOrderIdField = value;
                    this.RaisePropertyChanged("InsertionOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> LastModifiedByUserId {
            get {
                return this.LastModifiedByUserIdField;
            }
            set {
                if ((this.LastModifiedByUserIdField.Equals(value) != true)) {
                    this.LastModifiedByUserIdField = value;
                    this.RaisePropertyChanged("LastModifiedByUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModifiedTime {
            get {
                return this.LastModifiedTimeField;
            }
            set {
                if ((this.LastModifiedTimeField.Equals(value) != true)) {
                    this.LastModifiedTimeField = value;
                    this.RaisePropertyChanged("LastModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> NotificationThreshold {
            get {
                return this.NotificationThresholdField;
            }
            set {
                if ((this.NotificationThresholdField.Equals(value) != true)) {
                    this.NotificationThresholdField = value;
                    this.RaisePropertyChanged("NotificationThreshold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ReferenceId {
            get {
                return this.ReferenceIdField;
            }
            set {
                if ((this.ReferenceIdField.Equals(value) != true)) {
                    this.ReferenceIdField = value;
                    this.RaisePropertyChanged("ReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SpendCapAmount {
            get {
                return this.SpendCapAmountField;
            }
            set {
                if ((this.SpendCapAmountField.Equals(value) != true)) {
                    this.SpendCapAmountField = value;
                    this.RaisePropertyChanged("SpendCapAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrderStatus> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string PurchaseOrder {
            get {
                return this.PurchaseOrderField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseOrderField, value) != true)) {
                    this.PurchaseOrderField = value;
                    this.RaisePropertyChanged("PurchaseOrder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertionOrderStatus", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    public enum InsertionOrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingSystemReview = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingUserReview = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Declined = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Predicate", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    [System.SerializableAttribute()]
    public partial class Predicate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.PredicateOperator OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.PredicateOperator Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((this.OperatorField.Equals(value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PredicateOperator", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    public enum PredicateOperator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Equals = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEquals = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contains = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        In = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GreaterThanEquals = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LessThanEquals = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StartsWith = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotContains = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderBy", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    [System.SerializableAttribute()]
    public partial class OrderBy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.OrderByField FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SortOrder OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.OrderByField Field {
            get {
                return this.FieldField;
            }
            set {
                if ((this.FieldField.Equals(value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SortOrder Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderByField", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    public enum OrderByField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Id = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Name = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Number = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LifeCycleStatus = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortOrder", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    public enum SortOrder : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ascending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Descending = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paging", Namespace="https://bingads.microsoft.com/Customer/v9/Entities")]
    [System.SerializableAttribute()]
    public partial class Paging : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", ConfigurationName="V9.CustomerBillingService.ICustomerBillingService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface ICustomerBillingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBillingDocumentsInfo", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsInfoApiFault", Name="ApiFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiBatchFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsInfoApiBatchFault", Name="ApiBatchFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsInfoAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoResponse GetBillingDocumentsInfo(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBillingDocumentsInfo", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsInfoResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoResponse> GetBillingDocumentsInfoAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBillingDocuments", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsApiFault", Name="ApiFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiBatchFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsApiBatchFault", Name="ApiBatchFault")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsResponse GetBillingDocuments(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBillingDocuments", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetBillingDocume" +
            "ntsResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsResponse> GetBillingDocumentsAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDisplayInvoices", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetDisplayInvoic" +
            "esResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetDisplayInvoic" +
            "esApiFault", Name="ApiFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetDisplayInvoic" +
            "esAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiBatchFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetDisplayInvoic" +
            "esApiBatchFault", Name="ApiBatchFault")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesResponse GetDisplayInvoices(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetDisplayInvoices", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetDisplayInvoic" +
            "esResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesResponse> GetDisplayInvoicesAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AddInsertionOrder", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/AddInsertionOrde" +
            "rResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/AddInsertionOrde" +
            "rApiFault", Name="ApiFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/AddInsertionOrde" +
            "rAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderResponse AddInsertionOrder(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AddInsertionOrder", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/AddInsertionOrde" +
            "rResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderResponse> AddInsertionOrderAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdateInsertionOrder", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/UpdateInsertionO" +
            "rderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/UpdateInsertionO" +
            "rderAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/UpdateInsertionO" +
            "rderApiFault", Name="ApiFault")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderResponse UpdateInsertionOrder(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="UpdateInsertionOrder", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/UpdateInsertionO" +
            "rderResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderResponse> UpdateInsertionOrderAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetInsertionOrdersByAccount", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetInsertionOrde" +
            "rsByAccountResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetInsertionOrde" +
            "rsByAccountAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetInsertionOrde" +
            "rsByAccountApiFault", Name="ApiFault")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountResponse GetInsertionOrdersByAccount(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetInsertionOrdersByAccount", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetInsertionOrde" +
            "rsByAccountResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountResponse> GetInsertionOrdersByAccountAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SearchInsertionOrders", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/SearchInsertionO" +
            "rdersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/SearchInsertionO" +
            "rdersAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/SearchInsertionO" +
            "rdersApiFault", Name="ApiFault")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersResponse SearchInsertionOrders(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SearchInsertionOrders", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/SearchInsertionO" +
            "rdersResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersResponse> SearchInsertionOrdersAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetKOHIOInvoices", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetKOHIOInvoices" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiBatchFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetKOHIOInvoices" +
            "ApiBatchFault", Name="ApiBatchFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetKOHIOInvoices" +
            "AdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetKOHIOInvoices" +
            "ApiFault", Name="ApiFault")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesResponse GetKOHIOInvoices(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetKOHIOInvoices", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetKOHIOInvoices" +
            "Response")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesResponse> GetKOHIOInvoicesAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetAccountMonthlySpend", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetAccountMonthl" +
            "ySpendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AdApiFaultDetail), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetAccountMonthl" +
            "ySpendAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ApiFault), Action="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetAccountMonthl" +
            "ySpendApiFault", Name="ApiFault")]
        MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendResponse GetAccountMonthlySpend(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetAccountMonthlySpend", ReplyAction="https://bingads.microsoft.com/Billing/v9/ICustomerBillingService/GetAccountMonthl" +
            "ySpendResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendResponse> GetAccountMonthlySpendAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillingDocumentsInfoRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetBillingDocumentsInfoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public long[] AccountIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=1)]
        public System.DateTime StartDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=2)]
        public System.Nullable<System.DateTime> EndDate;
        
        public GetBillingDocumentsInfoRequest() {
        }
        
        public GetBillingDocumentsInfoRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, long[] AccountIds, System.DateTime StartDate, System.Nullable<System.DateTime> EndDate) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.AccountIds = AccountIds;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillingDocumentsInfoResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetBillingDocumentsInfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocumentInfo[] BillingDocumentsInfo;
        
        public GetBillingDocumentsInfoResponse() {
        }
        
        public GetBillingDocumentsInfoResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocumentInfo[] BillingDocumentsInfo) {
            this.TrackingId = TrackingId;
            this.BillingDocumentsInfo = BillingDocumentsInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillingDocumentsRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetBillingDocumentsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public long[] DocumentIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=1)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.DataType Type;
        
        public GetBillingDocumentsRequest() {
        }
        
        public GetBillingDocumentsRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, long[] DocumentIds, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.DataType Type) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.DocumentIds = DocumentIds;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillingDocumentsResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetBillingDocumentsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocument[] BillingDocuments;
        
        public GetBillingDocumentsResponse() {
        }
        
        public GetBillingDocumentsResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocument[] BillingDocuments) {
            this.TrackingId = TrackingId;
            this.BillingDocuments = BillingDocuments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDisplayInvoicesRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetDisplayInvoicesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public long[] InvoiceIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=1)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.DataType Type;
        
        public GetDisplayInvoicesRequest() {
        }
        
        public GetDisplayInvoicesRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, long[] InvoiceIds, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.DataType Type) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.InvoiceIds = InvoiceIds;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDisplayInvoicesResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetDisplayInvoicesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocument[] BillingDocuments;
        
        public GetDisplayInvoicesResponse() {
        }
        
        public GetDisplayInvoicesResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocument[] BillingDocuments) {
            this.TrackingId = TrackingId;
            this.BillingDocuments = BillingDocuments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddInsertionOrderRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class AddInsertionOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder InsertionOrder;
        
        public AddInsertionOrderRequest() {
        }
        
        public AddInsertionOrderRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder InsertionOrder) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.InsertionOrder = InsertionOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddInsertionOrderResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class AddInsertionOrderResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public long InsertionOrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=1)]
        public System.DateTime CreateTime;
        
        public AddInsertionOrderResponse() {
        }
        
        public AddInsertionOrderResponse(string TrackingId, long InsertionOrderId, System.DateTime CreateTime) {
            this.TrackingId = TrackingId;
            this.InsertionOrderId = InsertionOrderId;
            this.CreateTime = CreateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateInsertionOrderRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class UpdateInsertionOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder InsertionOrder;
        
        public UpdateInsertionOrderRequest() {
        }
        
        public UpdateInsertionOrderRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder InsertionOrder) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.InsertionOrder = InsertionOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateInsertionOrderResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class UpdateInsertionOrderResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public System.DateTime LastModifiedTime;
        
        public UpdateInsertionOrderResponse() {
        }
        
        public UpdateInsertionOrderResponse(string TrackingId, System.DateTime LastModifiedTime) {
            this.TrackingId = TrackingId;
            this.LastModifiedTime = LastModifiedTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInsertionOrdersByAccountRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetInsertionOrdersByAccountRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public long AccountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=1)]
        public long[] InsertionOrderIds;
        
        public GetInsertionOrdersByAccountRequest() {
        }
        
        public GetInsertionOrdersByAccountRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, long AccountId, long[] InsertionOrderIds) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.AccountId = AccountId;
            this.InsertionOrderIds = InsertionOrderIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetInsertionOrdersByAccountResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetInsertionOrdersByAccountResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder[] InsertionOrders;
        
        public GetInsertionOrdersByAccountResponse() {
        }
        
        public GetInsertionOrdersByAccountResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder[] InsertionOrders) {
            this.TrackingId = TrackingId;
            this.InsertionOrders = InsertionOrders;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchInsertionOrdersRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class SearchInsertionOrdersRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.Predicate[] Predicates;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=1)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.OrderBy[] Ordering;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=2)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.Paging PageInfo;
        
        public SearchInsertionOrdersRequest() {
        }
        
        public SearchInsertionOrdersRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.Predicate[] Predicates, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.OrderBy[] Ordering, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.Paging PageInfo) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.Predicates = Predicates;
            this.Ordering = Ordering;
            this.PageInfo = PageInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchInsertionOrdersResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class SearchInsertionOrdersResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder[] InsertionOrders;
        
        public SearchInsertionOrdersResponse() {
        }
        
        public SearchInsertionOrdersResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.InsertionOrder[] InsertionOrders) {
            this.TrackingId = TrackingId;
            this.InsertionOrders = InsertionOrders;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKOHIOInvoicesRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetKOHIOInvoicesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public string[] InvoiceIds;
        
        public GetKOHIOInvoicesRequest() {
        }
        
        public GetKOHIOInvoicesRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, string[] InvoiceIds) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.InvoiceIds = InvoiceIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKOHIOInvoicesResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetKOHIOInvoicesResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocument[] BillingDocuments;
        
        public GetKOHIOInvoicesResponse() {
        }
        
        public GetKOHIOInvoicesResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.BillingDocument[] BillingDocuments) {
            this.TrackingId = TrackingId;
            this.BillingDocuments = BillingDocuments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountMonthlySpendRequest", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetAccountMonthlySpendRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public long AccountId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=1)]
        public System.DateTime MonthYear;
        
        public GetAccountMonthlySpendRequest() {
        }
        
        public GetAccountMonthlySpendRequest(string ApplicationToken, string AuthenticationToken, string DeveloperToken, string Password, string UserName, long AccountId, System.DateTime MonthYear) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.AccountId = AccountId;
            this.MonthYear = MonthYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountMonthlySpendResponse", WrapperNamespace="https://bingads.microsoft.com/Billing/v9", IsWrapped=true)]
    public partial class GetAccountMonthlySpendResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/Billing/v9")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/Billing/v9", Order=0)]
        public double Amount;
        
        public GetAccountMonthlySpendResponse() {
        }
        
        public GetAccountMonthlySpendResponse(string TrackingId, double Amount) {
            this.TrackingId = TrackingId;
            this.Amount = Amount;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerBillingServiceChannel : MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ICustomerBillingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerBillingServiceClient : System.ServiceModel.ClientBase<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ICustomerBillingService>, MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.ICustomerBillingService {
        
        public CustomerBillingServiceClient() {
        }
        
        public CustomerBillingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerBillingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerBillingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerBillingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoResponse GetBillingDocumentsInfo(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoRequest request) {
            return base.Channel.GetBillingDocumentsInfo(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoResponse> GetBillingDocumentsInfoAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsInfoRequest request) {
            return base.Channel.GetBillingDocumentsInfoAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsResponse GetBillingDocuments(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsRequest request) {
            return base.Channel.GetBillingDocuments(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsResponse> GetBillingDocumentsAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetBillingDocumentsRequest request) {
            return base.Channel.GetBillingDocumentsAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesResponse GetDisplayInvoices(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesRequest request) {
            return base.Channel.GetDisplayInvoices(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesResponse> GetDisplayInvoicesAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetDisplayInvoicesRequest request) {
            return base.Channel.GetDisplayInvoicesAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderResponse AddInsertionOrder(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderRequest request) {
            return base.Channel.AddInsertionOrder(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderResponse> AddInsertionOrderAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.AddInsertionOrderRequest request) {
            return base.Channel.AddInsertionOrderAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderResponse UpdateInsertionOrder(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderRequest request) {
            return base.Channel.UpdateInsertionOrder(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderResponse> UpdateInsertionOrderAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.UpdateInsertionOrderRequest request) {
            return base.Channel.UpdateInsertionOrderAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountResponse GetInsertionOrdersByAccount(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountRequest request) {
            return base.Channel.GetInsertionOrdersByAccount(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountResponse> GetInsertionOrdersByAccountAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetInsertionOrdersByAccountRequest request) {
            return base.Channel.GetInsertionOrdersByAccountAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersResponse SearchInsertionOrders(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersRequest request) {
            return base.Channel.SearchInsertionOrders(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersResponse> SearchInsertionOrdersAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.SearchInsertionOrdersRequest request) {
            return base.Channel.SearchInsertionOrdersAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesResponse GetKOHIOInvoices(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesRequest request) {
            return base.Channel.GetKOHIOInvoices(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesResponse> GetKOHIOInvoicesAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetKOHIOInvoicesRequest request) {
            return base.Channel.GetKOHIOInvoicesAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendResponse GetAccountMonthlySpend(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendRequest request) {
            return base.Channel.GetAccountMonthlySpend(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendResponse> GetAccountMonthlySpendAsync(MicrosoftOnline.Ads.BingAdsApi.V9.CustomerBillingService.GetAccountMonthlySpendRequest request) {
            return base.Channel.GetAccountMonthlySpendAsync(request);
        }
    }
}
