//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicrosoftOnline.Ads.BingAdsApi.V10.BulkService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompressionType", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    public enum CompressionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zip = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GZip = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataScope", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    public enum DataScope : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EntityData = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EntityPerformanceData = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QualityScoreData = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BidSuggestionsData = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadFileType", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    public enum DownloadFileType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Csv = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tsv = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkDownloadEntity", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    public enum BulkDownloadEntity : long {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Campaigns = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroups = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ads = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Keywords = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeKeywords = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeKeywords = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignTargets = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupTargets = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeSites = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupNegativeSites = 512,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignSiteLinksAdExtensions = 1024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignLocationAdExtensions = 2048,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignCallAdExtensions = 4096,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupSiteLinksAdExtensions = 8192,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LocationAdExtensions = 16384,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CallAdExtensions = 32768,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SiteLinksAdExtensions = 65536,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NegativeKeywordLists = 131072,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SharedNegativeKeywords = 262144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNegativeKeywordListAssociations = 524288,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImageAdExtensions = 1048576,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignImageAdExtensions = 2097152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupImageAdExtensions = 4194304,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AppAdExtensions = 8388608,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupAppAdExtensions = 16777216,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignAppAdExtensions = 33554432,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdGroupProductPartitions = 67108864,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignProductScopes = 134217728,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PerformanceStatsDateRange", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    [System.SerializableAttribute()]
    public partial class PerformanceStatsDateRange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.Date CustomDateRangeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.Date CustomDateRangeStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ReportTimePeriod> PredefinedTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.Date CustomDateRangeEnd {
            get {
                return this.CustomDateRangeEndField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDateRangeEndField, value) != true)) {
                    this.CustomDateRangeEndField = value;
                    this.RaisePropertyChanged("CustomDateRangeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.Date CustomDateRangeStart {
            get {
                return this.CustomDateRangeStartField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDateRangeStartField, value) != true)) {
                    this.CustomDateRangeStartField = value;
                    this.RaisePropertyChanged("CustomDateRangeStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ReportTimePeriod> PredefinedTime {
            get {
                return this.PredefinedTimeField;
            }
            set {
                if ((this.PredefinedTimeField.Equals(value) != true)) {
                    this.PredefinedTimeField = value;
                    this.RaisePropertyChanged("PredefinedTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Date", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    [System.SerializableAttribute()]
    public partial class Date : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DayField;
        
        private int MonthField;
        
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Month {
            get {
                return this.MonthField;
            }
            set {
                if ((this.MonthField.Equals(value) != true)) {
                    this.MonthField = value;
                    this.RaisePropertyChanged("Month");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportTimePeriod", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    public enum ReportTimePeriod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Today = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yesterday = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastSevenDays = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThisWeek = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastWeek = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastFourWeeks = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThisMonth = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastMonth = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastThreeMonths = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastSixMonths = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThisYear = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastYear = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationFault", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiFaultDetail))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApiFaultDetail))]
    public partial class ApplicationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingId {
            get {
                return this.TrackingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingIdField, value) != true)) {
                    this.TrackingIdField = value;
                    this.RaisePropertyChanged("TrackingId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    public partial class AdApiFaultDetail : MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApplicationFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiError[] ErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiFaultDetail", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    [System.SerializableAttribute()]
    public partial class ApiFaultDetail : MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApplicationFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.BatchError[] BatchErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.OperationError[] OperationErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.BatchError[] BatchErrors {
            get {
                return this.BatchErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchErrorsField, value) != true)) {
                    this.BatchErrorsField = value;
                    this.RaisePropertyChanged("BatchErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.OperationError[] OperationErrors {
            get {
                return this.OperationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationErrorsField, value) != true)) {
                    this.OperationErrorsField = value;
                    this.RaisePropertyChanged("OperationErrors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchError", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.EditorialError))]
    public partial class BatchError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<string, string>[] ForwardCompatibilityMapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldPath {
            get {
                return this.FieldPathField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldPathField, value) != true)) {
                    this.FieldPathField = value;
                    this.RaisePropertyChanged("FieldPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] ForwardCompatibilityMap {
            get {
                return this.ForwardCompatibilityMapField;
            }
            set {
                if ((object.ReferenceEquals(this.ForwardCompatibilityMapField, value) != true)) {
                    this.ForwardCompatibilityMapField = value;
                    this.RaisePropertyChanged("ForwardCompatibilityMap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationError", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    [System.SerializableAttribute()]
    public partial class OperationError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdApiError", Namespace="https://adapi.microsoft.com")]
    [System.SerializableAttribute()]
    public partial class AdApiError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditorialError", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    [System.SerializableAttribute()]
    public partial class EditorialError : MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.BatchError {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AppealableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisapprovedTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublisherCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReasonCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Appealable {
            get {
                return this.AppealableField;
            }
            set {
                if ((this.AppealableField.Equals(value) != true)) {
                    this.AppealableField = value;
                    this.RaisePropertyChanged("Appealable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisapprovedText {
            get {
                return this.DisapprovedTextField;
            }
            set {
                if ((object.ReferenceEquals(this.DisapprovedTextField, value) != true)) {
                    this.DisapprovedTextField = value;
                    this.RaisePropertyChanged("DisapprovedText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublisherCountry {
            get {
                return this.PublisherCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherCountryField, value) != true)) {
                    this.PublisherCountryField = value;
                    this.RaisePropertyChanged("PublisherCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReasonCode {
            get {
                return this.ReasonCodeField;
            }
            set {
                if ((this.ReasonCodeField.Equals(value) != true)) {
                    this.ReasonCodeField = value;
                    this.RaisePropertyChanged("ReasonCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignScope", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    [System.SerializableAttribute()]
    public partial class CampaignScope : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ParentAccountIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((this.CampaignIdField.Equals(value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ParentAccountId {
            get {
                return this.ParentAccountIdField;
            }
            set {
                if ((this.ParentAccountIdField.Equals(value) != true)) {
                    this.ParentAccountIdField = value;
                    this.RaisePropertyChanged("ParentAccountId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMode", Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
    public enum ResponseMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorsOnly = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorsAndResults = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", ConfigurationName="V10.BulkService.IBulkService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IBulkService {
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByAccountIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByAccountIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByAccountIdsApiFaultDetail3Fault", Name="ApiFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByAccountIdsAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsResponse DownloadCampaignsByAccountIds(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByAccountIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByAccountIdsResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsResponse> DownloadCampaignsByAccountIdsAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByCampaignIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsApiFaultDetail3Fault", Name="ApiFaultDetail")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsResponse DownloadCampaignsByCampaignIds(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadCampaignsByCampaignIds", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/DownloadCampaig" +
            "nsByCampaignIdsResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsResponse> DownloadCampaignsByCampaignIdsAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkDownloadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkDownload" +
            "StatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkDownload" +
            "StatusAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkDownload" +
            "StatusApiFaultDetail3Fault", Name="ApiFaultDetail")]
        MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusResponse GetBulkDownloadStatus(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkDownloadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkDownload" +
            "StatusResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusResponse> GetBulkDownloadStatusAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadUrl", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadUr" +
            "lResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadUr" +
            "lAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadUr" +
            "lApiFaultDetail3Fault", Name="ApiFaultDetail")]
        MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlResponse GetBulkUploadUrl(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadUrl", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadUr" +
            "lResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlResponse> GetBulkUploadUrlAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadSt" +
            "atusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.AdApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadSt" +
            "atusAdApiFaultDetailFault", Name="AdApiFaultDetail", Namespace="https://adapi.microsoft.com")]
        [System.ServiceModel.FaultContractAttribute(typeof(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ApiFaultDetail), Action="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadSt" +
            "atusApiFaultDetail3Fault", Name="ApiFaultDetail")]
        MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusResponse GetBulkUploadStatus(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBulkUploadStatus", ReplyAction="https://bingads.microsoft.com/CampaignManagement/v10/IBulkService/GetBulkUploadSt" +
            "atusResponse")]
        System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusResponse> GetBulkUploadStatusAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByAccountIdsRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class DownloadCampaignsByAccountIdsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public long[] AccountIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=1)]
        public System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.CompressionType> CompressionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=2)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DataScope DataScope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=3)]
        public System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadFileType> DownloadFileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=4)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.BulkDownloadEntity Entities;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=5)]
        public string FormatVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=6)]
        public System.Nullable<System.DateTime> LastSyncTimeInUTC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=7)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.PerformanceStatsDateRange PerformanceStatsDateRange;
        
        public DownloadCampaignsByAccountIdsRequest() {
        }
        
        public DownloadCampaignsByAccountIdsRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, long[] AccountIds, System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.CompressionType> CompressionType, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DataScope DataScope, System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadFileType> DownloadFileType, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.BulkDownloadEntity Entities, string FormatVersion, System.Nullable<System.DateTime> LastSyncTimeInUTC, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.PerformanceStatsDateRange PerformanceStatsDateRange) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.AccountIds = AccountIds;
            this.CompressionType = CompressionType;
            this.DataScope = DataScope;
            this.DownloadFileType = DownloadFileType;
            this.Entities = Entities;
            this.FormatVersion = FormatVersion;
            this.LastSyncTimeInUTC = LastSyncTimeInUTC;
            this.PerformanceStatsDateRange = PerformanceStatsDateRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByAccountIdsResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class DownloadCampaignsByAccountIdsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public string DownloadRequestId;
        
        public DownloadCampaignsByAccountIdsResponse() {
        }
        
        public DownloadCampaignsByAccountIdsResponse(string TrackingId, string DownloadRequestId) {
            this.TrackingId = TrackingId;
            this.DownloadRequestId = DownloadRequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByCampaignIdsRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class DownloadCampaignsByCampaignIdsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.CampaignScope[] Campaigns;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=1)]
        public System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.CompressionType> CompressionType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=2)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DataScope DataScope;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=3)]
        public System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadFileType> DownloadFileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=4)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.BulkDownloadEntity Entities;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=5)]
        public string FormatVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=6)]
        public System.Nullable<System.DateTime> LastSyncTimeInUTC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=7)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.PerformanceStatsDateRange PerformanceStatsDateRange;
        
        public DownloadCampaignsByCampaignIdsRequest() {
        }
        
        public DownloadCampaignsByCampaignIdsRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.CampaignScope[] Campaigns, System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.CompressionType> CompressionType, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DataScope DataScope, System.Nullable<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadFileType> DownloadFileType, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.BulkDownloadEntity Entities, string FormatVersion, System.Nullable<System.DateTime> LastSyncTimeInUTC, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.PerformanceStatsDateRange PerformanceStatsDateRange) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.Campaigns = Campaigns;
            this.CompressionType = CompressionType;
            this.DataScope = DataScope;
            this.DownloadFileType = DownloadFileType;
            this.Entities = Entities;
            this.FormatVersion = FormatVersion;
            this.LastSyncTimeInUTC = LastSyncTimeInUTC;
            this.PerformanceStatsDateRange = PerformanceStatsDateRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadCampaignsByCampaignIdsResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class DownloadCampaignsByCampaignIdsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public string DownloadRequestId;
        
        public DownloadCampaignsByCampaignIdsResponse() {
        }
        
        public DownloadCampaignsByCampaignIdsResponse(string TrackingId, string DownloadRequestId) {
            this.TrackingId = TrackingId;
            this.DownloadRequestId = DownloadRequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkDownloadStatusRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class GetBulkDownloadStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public string RequestId;
        
        public GetBulkDownloadStatusRequest() {
        }
        
        public GetBulkDownloadStatusRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, string RequestId) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkDownloadStatusResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class GetBulkDownloadStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.OperationError[] Errors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=1)]
        public System.Collections.Generic.KeyValuePair<string, string>[] ForwardCompatibilityMap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=2)]
        public int PercentComplete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=3)]
        public string RequestStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=4)]
        public string ResultFileUrl;
        
        public GetBulkDownloadStatusResponse() {
        }
        
        public GetBulkDownloadStatusResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.OperationError[] Errors, System.Collections.Generic.KeyValuePair<string, string>[] ForwardCompatibilityMap, int PercentComplete, string RequestStatus, string ResultFileUrl) {
            this.TrackingId = TrackingId;
            this.Errors = Errors;
            this.ForwardCompatibilityMap = ForwardCompatibilityMap;
            this.PercentComplete = PercentComplete;
            this.RequestStatus = RequestStatus;
            this.ResultFileUrl = ResultFileUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadUrlRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class GetBulkUploadUrlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ResponseMode ResponseMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=1)]
        public long AccountId;
        
        public GetBulkUploadUrlRequest() {
        }
        
        public GetBulkUploadUrlRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.ResponseMode ResponseMode, long AccountId) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.ResponseMode = ResponseMode;
            this.AccountId = AccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadUrlResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class GetBulkUploadUrlResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public string RequestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=1)]
        public string UploadUrl;
        
        public GetBulkUploadUrlResponse() {
        }
        
        public GetBulkUploadUrlResponse(string TrackingId, string RequestId, string UploadUrl) {
            this.TrackingId = TrackingId;
            this.RequestId = RequestId;
            this.UploadUrl = UploadUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadStatusRequest", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class GetBulkUploadStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string ApplicationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string AuthenticationToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerAccountId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string CustomerId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string DeveloperToken;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public string RequestId;
        
        public GetBulkUploadStatusRequest() {
        }
        
        public GetBulkUploadStatusRequest(string ApplicationToken, string AuthenticationToken, string CustomerAccountId, string CustomerId, string DeveloperToken, string Password, string UserName, string RequestId) {
            this.ApplicationToken = ApplicationToken;
            this.AuthenticationToken = AuthenticationToken;
            this.CustomerAccountId = CustomerAccountId;
            this.CustomerId = CustomerId;
            this.DeveloperToken = DeveloperToken;
            this.Password = Password;
            this.UserName = UserName;
            this.RequestId = RequestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkUploadStatusResponse", WrapperNamespace="https://bingads.microsoft.com/CampaignManagement/v10", IsWrapped=true)]
    public partial class GetBulkUploadStatusResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10")]
        public string TrackingId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=0)]
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.OperationError[] Errors;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=1)]
        public System.Collections.Generic.KeyValuePair<string, string>[] ForwardCompatibilityMap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=2)]
        public int PercentComplete;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=3)]
        public string RequestStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://bingads.microsoft.com/CampaignManagement/v10", Order=4)]
        public string ResultFileUrl;
        
        public GetBulkUploadStatusResponse() {
        }
        
        public GetBulkUploadStatusResponse(string TrackingId, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.OperationError[] Errors, System.Collections.Generic.KeyValuePair<string, string>[] ForwardCompatibilityMap, int PercentComplete, string RequestStatus, string ResultFileUrl) {
            this.TrackingId = TrackingId;
            this.Errors = Errors;
            this.ForwardCompatibilityMap = ForwardCompatibilityMap;
            this.PercentComplete = PercentComplete;
            this.RequestStatus = RequestStatus;
            this.ResultFileUrl = ResultFileUrl;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBulkServiceChannel : MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.IBulkService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BulkServiceClient : System.ServiceModel.ClientBase<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.IBulkService>, MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.IBulkService {
        
        public BulkServiceClient() {
        }
        
        public BulkServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BulkServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BulkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BulkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsResponse DownloadCampaignsByAccountIds(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsRequest request) {
            return base.Channel.DownloadCampaignsByAccountIds(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsResponse> DownloadCampaignsByAccountIdsAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByAccountIdsRequest request) {
            return base.Channel.DownloadCampaignsByAccountIdsAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsResponse DownloadCampaignsByCampaignIds(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsRequest request) {
            return base.Channel.DownloadCampaignsByCampaignIds(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsResponse> DownloadCampaignsByCampaignIdsAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.DownloadCampaignsByCampaignIdsRequest request) {
            return base.Channel.DownloadCampaignsByCampaignIdsAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusResponse GetBulkDownloadStatus(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusRequest request) {
            return base.Channel.GetBulkDownloadStatus(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusResponse> GetBulkDownloadStatusAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkDownloadStatusRequest request) {
            return base.Channel.GetBulkDownloadStatusAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlResponse GetBulkUploadUrl(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlRequest request) {
            return base.Channel.GetBulkUploadUrl(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlResponse> GetBulkUploadUrlAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadUrlRequest request) {
            return base.Channel.GetBulkUploadUrlAsync(request);
        }
        
        public MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusResponse GetBulkUploadStatus(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusRequest request) {
            return base.Channel.GetBulkUploadStatus(request);
        }
        
        public System.Threading.Tasks.Task<MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusResponse> GetBulkUploadStatusAsync(MicrosoftOnline.Ads.BingAdsApi.V10.BulkService.GetBulkUploadStatusRequest request) {
            return base.Channel.GetBulkUploadStatusAsync(request);
        }
    }
}
